Dev
Dimaska30/hello_weather pull request #1
Opened 2022-07-09 12:30 UTC by Dimaska30

Half-baked application

2022-07-09 14:08 UTC, rvachev requested changes
круто пишешь код!
Я изначально даже не поверил и пошел искать может где-то скатал, но так и не нашел. Видимо так круто скатал, что я не узнал, либо сам по себе крутой прогер
Ну в общем нашел пару замечаний - исправляешь ставлю 5

2022-07-09 14:08 UTC, rvachev commented on lib/data/api/model/city_api.dart
> +  final num lat;
лучше явно указывать численные переменные - int или double

2022-07-09 14:08 UTC, rvachev commented on lib/data/api/service/open_weather_service.dart
> +  static const _BASE_URL = "http://api.openweathermap.org";
я бы не игнорил предупреждения линтера, а реально использовал бы lowerCamelCase для нейминга

2022-07-09 14:08 UTC, rvachev commented on lib/presentation/city_choise.dart
> +  Widget city_listView(City city) {
методы должны именоваться как lowerCamelCase, а не snake_case

2022-07-09 14:08 UTC, rvachev commented on lib/presentation/forecast_page.dart
> +    // ignore: prefer_const_constructors
тут зачем игнор?

2022-07-09 14:08 UTC, rvachev commented on lib/presentation/line_chart.dart
> +              Color(0xff2c274c),
цвета лучше убирать в отдельный класс в константу

2022-07-09 14:08 UTC, rvachev commented on lib/presentation/city_choise.dart
> +class CityChoise extends StatefulWidget {
этот класс вообще нигде не используется

2022-07-09 14:08 UTC, rvachev commented on lib/presentation/forecast_page.dart
> +  _DailyForecastPageState createState() => _DailyForecastPageState();
тут не должно быть игнора
и надо должно быть `State<DailyForecastPage>` вместо `_DailyForecastPageState `

2022-07-09 14:08 UTC, rvachev commented on lib/presentation/city_choise.dart
> +  _CityChoiseState createState() => _CityChoiseState();
и здесь

2022-07-09 14:08 UTC, rvachev commented on lib/presentation/home.dart
> +  _HomeState createState() => _HomeState();
и здесь

2022-07-09 23:40 UTC, Dimaska30 commented on lib/presentation/city_choise.dart
> +  _CityChoiseState createState() => _CityChoiseState();
Выполнил

2022-07-09 23:40 UTC, Dimaska30 commented on lib/presentation/forecast_page.dart
> +  _DailyForecastPageState createState() => _DailyForecastPageState();
Выполнил

2022-07-09 23:41 UTC, Dimaska30 commented on lib/presentation/forecast_page.dart
> +    // ignore: prefer_const_constructors
Убрал

2022-07-09 23:46 UTC, Dimaska30 commented on lib/data/api/service/open_weather_service.dart
> +  static const _BASE_URL = "http://api.openweathermap.org";
Исправил

2022-07-09 23:46 UTC, Dimaska30 commented on lib/data/api/model/city_api.dart
> +  final num lat;
Исправил

2022-07-09 23:53 UTC, Dimaska30 commented on lib/presentation/city_choise.dart
> +  Widget city_listView(City city) {
Исправил

2022-07-10 00:14 UTC, Dimaska30 commented on lib/presentation/line_chart.dart
> +              Color(0xff2c274c),
Выполнил

2022-07-10 00:15 UTC, Dimaska30 commented on lib/presentation/city_choise.dart
> +class CityChoise extends StatefulWidget {
Выполнил

2022-07-10 00:16 UTC, Dimaska30 commented on lib/presentation/city_choise.dart
> +class CityChoise extends StatefulWidget {
Точнее, убрал

2022-07-10 00:16 UTC, closed without merging